// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recordData.proto

package com.example.grpc.recordDataService;

public final class recordDataServiceProto {
  private recordDataServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_recordDataService_RecordSensorDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_recordDataService_RecordSensorDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_recordDataService_RecordSensorDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_recordDataService_RecordSensorDataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020recordData.proto\022\"com.example.grpc.rec" +
      "ordDataService\"V\n\027RecordSensorDataReques" +
      "t\022\023\n\013temperature\030\001 \001(\005\022\024\n\014soilHumidity\030\002" +
      " \001(\005\022\020\n\010dateTime\030\003 \001(\t\"+\n\030RecordSensorDa" +
      "taResponse\022\017\n\007message\030\001 \001(\t2\245\001\n\023Register" +
      "DataService\022\215\001\n\016sendRecordData\022;.com.exa" +
      "mple.grpc.recordDataService.RecordSensor" +
      "DataRequest\032<.com.example.grpc.recordDat" +
      "aService.RecordSensorDataResponse(\001B>\n\"c" +
      "om.example.grpc.recordDataServiceB\026recor" +
      "dDataServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_example_grpc_recordDataService_RecordSensorDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_grpc_recordDataService_RecordSensorDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_recordDataService_RecordSensorDataRequest_descriptor,
        new java.lang.String[] { "Temperature", "SoilHumidity", "DateTime", });
    internal_static_com_example_grpc_recordDataService_RecordSensorDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_grpc_recordDataService_RecordSensorDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_recordDataService_RecordSensorDataResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
