// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recordData.proto

package com.example.grpc.recordDataService;

public interface RecordSensorDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.recordDataService.RecordSensorDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
