// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fanStatus.proto

package com.example.grpc.fanStatus;

public final class fanStatusProto {
  private fanStatusProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_fanStatus_StreamTemperatureToFan_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_fanStatus_StreamTemperatureToFan_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_fanStatus_StreamFanStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_fanStatus_StreamFanStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017fanStatus.proto\022\032com.example.grpc.fanS" +
      "tatus\"-\n\026StreamTemperatureToFan\022\023\n\013tempe" +
      "rature\030\001 \001(\005\"\"\n\017StreamFanStatus\022\017\n\007messa" +
      "ge\030\001 \001(\0102\246\001\n\035StreamingTemperatureFanStat" +
      "us\022\204\001\n\035StreamingTemperatureFanStatus\0222.c" +
      "om.example.grpc.fanStatus.StreamTemperat" +
      "ureToFan\032+.com.example.grpc.fanStatus.St" +
      "reamFanStatus(\0010\001B.\n\032com.example.grpc.fa" +
      "nStatusB\016fanStatusProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_example_grpc_fanStatus_StreamTemperatureToFan_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_grpc_fanStatus_StreamTemperatureToFan_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_fanStatus_StreamTemperatureToFan_descriptor,
        new java.lang.String[] { "Temperature", });
    internal_static_com_example_grpc_fanStatus_StreamFanStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_grpc_fanStatus_StreamFanStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_fanStatus_StreamFanStatus_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
