// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fanStatus.proto

package com.example.grpc.fanStatus;

public interface StreamTemperatureToFanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.fanStatus.StreamTemperatureToFan)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 temperature = 1;</code>
   */
  int getTemperature();
}
