// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fanStatus.proto

package com.example.grpc.fanStatus;

public interface StreamFanStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.fanStatus.StreamFanStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool message = 1;</code>
   */
  boolean getMessage();
}
