// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: humiditySensor.proto

package com.example.grpc.humiditySensor;

public final class humidityProto {
  private humidityProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_humiditySensor_UnaryHumidityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_humiditySensor_UnaryHumidityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_humiditySensor_UnaryHumidityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_humiditySensor_UnaryHumidityResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_humiditySensor_StreamHumidityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_humiditySensor_StreamHumidityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_humiditySensor_StreamHumidityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_humiditySensor_StreamHumidityResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024humiditySensor.proto\022\037com.example.grpc" +
      ".humiditySensor\"(\n\024UnaryHumidityRequest\022" +
      "\020\n\010humidity\030\001 \001(\001\"(\n\025UnaryHumidityRespon" +
      "se\022\017\n\007message\030\001 \001(\t\"/\n\025StreamHumidityReq" +
      "uest\022\026\n\016streamHumidity\030\001 \001(\001\")\n\026StreamHu" +
      "midityResponse\022\017\n\007message\030\001 \001(\t2\252\002\n\025Humi" +
      "ditySensorService\022\203\001\n\022getCurrentHumidity" +
      "\0225.com.example.grpc.humiditySensor.Unary" +
      "HumidityRequest\0326.com.example.grpc.humid" +
      "itySensor.UnaryHumidityResponse\022\212\001\n\025stre" +
      "amCurrentHumidity\0226.com.example.grpc.hum" +
      "iditySensor.StreamHumidityRequest\0327.com." +
      "example.grpc.humiditySensor.StreamHumidi" +
      "tyResponse0\001B2\n\037com.example.grpc.humidit" +
      "ySensorB\rhumidityProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_example_grpc_humiditySensor_UnaryHumidityRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_grpc_humiditySensor_UnaryHumidityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_humiditySensor_UnaryHumidityRequest_descriptor,
        new java.lang.String[] { "Humidity", });
    internal_static_com_example_grpc_humiditySensor_UnaryHumidityResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_grpc_humiditySensor_UnaryHumidityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_humiditySensor_UnaryHumidityResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_example_grpc_humiditySensor_StreamHumidityRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_grpc_humiditySensor_StreamHumidityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_humiditySensor_StreamHumidityRequest_descriptor,
        new java.lang.String[] { "StreamHumidity", });
    internal_static_com_example_grpc_humiditySensor_StreamHumidityResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_example_grpc_humiditySensor_StreamHumidityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_humiditySensor_StreamHumidityResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
