// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: humiditySensor.proto

package com.example.grpc.humiditySensor;

public interface StreamHumidityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.humiditySensor.StreamHumidityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 humidity = 1;</code>
   */
  int getHumidity();
}
