// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: humiditySensor.proto

package com.example.grpc.humiditySensor;

/**
 * Protobuf type {@code com.example.grpc.humiditySensor.StreamHumidityRequest}
 */
public  final class StreamHumidityRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.grpc.humiditySensor.StreamHumidityRequest)
    StreamHumidityRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StreamHumidityRequest.newBuilder() to construct.
  private StreamHumidityRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StreamHumidityRequest() {
    streamHumidity_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StreamHumidityRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            streamHumidity_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.grpc.humiditySensor.humidityProto.internal_static_com_example_grpc_humiditySensor_StreamHumidityRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.grpc.humiditySensor.humidityProto.internal_static_com_example_grpc_humiditySensor_StreamHumidityRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.grpc.humiditySensor.StreamHumidityRequest.class, com.example.grpc.humiditySensor.StreamHumidityRequest.Builder.class);
  }

  public static final int STREAMHUMIDITY_FIELD_NUMBER = 1;
  private double streamHumidity_;
  /**
   * <code>double streamHumidity = 1;</code>
   */
  public double getStreamHumidity() {
    return streamHumidity_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (streamHumidity_ != 0D) {
      output.writeDouble(1, streamHumidity_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (streamHumidity_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, streamHumidity_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.grpc.humiditySensor.StreamHumidityRequest)) {
      return super.equals(obj);
    }
    com.example.grpc.humiditySensor.StreamHumidityRequest other = (com.example.grpc.humiditySensor.StreamHumidityRequest) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getStreamHumidity())
        == java.lang.Double.doubleToLongBits(
            other.getStreamHumidity()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STREAMHUMIDITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getStreamHumidity()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.grpc.humiditySensor.StreamHumidityRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.humiditySensor.StreamHumidityRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.humiditySensor.StreamHumidityRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.humiditySensor.StreamHumidityRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.humiditySensor.StreamHumidityRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.humiditySensor.StreamHumidityRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.humiditySensor.StreamHumidityRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.humiditySensor.StreamHumidityRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.humiditySensor.StreamHumidityRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.grpc.humiditySensor.StreamHumidityRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.humiditySensor.StreamHumidityRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.humiditySensor.StreamHumidityRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.grpc.humiditySensor.StreamHumidityRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.grpc.humiditySensor.StreamHumidityRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.grpc.humiditySensor.StreamHumidityRequest)
      com.example.grpc.humiditySensor.StreamHumidityRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.humiditySensor.humidityProto.internal_static_com_example_grpc_humiditySensor_StreamHumidityRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.humiditySensor.humidityProto.internal_static_com_example_grpc_humiditySensor_StreamHumidityRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.humiditySensor.StreamHumidityRequest.class, com.example.grpc.humiditySensor.StreamHumidityRequest.Builder.class);
    }

    // Construct using com.example.grpc.humiditySensor.StreamHumidityRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      streamHumidity_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.grpc.humiditySensor.humidityProto.internal_static_com_example_grpc_humiditySensor_StreamHumidityRequest_descriptor;
    }

    @java.lang.Override
    public com.example.grpc.humiditySensor.StreamHumidityRequest getDefaultInstanceForType() {
      return com.example.grpc.humiditySensor.StreamHumidityRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.grpc.humiditySensor.StreamHumidityRequest build() {
      com.example.grpc.humiditySensor.StreamHumidityRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.grpc.humiditySensor.StreamHumidityRequest buildPartial() {
      com.example.grpc.humiditySensor.StreamHumidityRequest result = new com.example.grpc.humiditySensor.StreamHumidityRequest(this);
      result.streamHumidity_ = streamHumidity_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.grpc.humiditySensor.StreamHumidityRequest) {
        return mergeFrom((com.example.grpc.humiditySensor.StreamHumidityRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.grpc.humiditySensor.StreamHumidityRequest other) {
      if (other == com.example.grpc.humiditySensor.StreamHumidityRequest.getDefaultInstance()) return this;
      if (other.getStreamHumidity() != 0D) {
        setStreamHumidity(other.getStreamHumidity());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.grpc.humiditySensor.StreamHumidityRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.grpc.humiditySensor.StreamHumidityRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double streamHumidity_ ;
    /**
     * <code>double streamHumidity = 1;</code>
     */
    public double getStreamHumidity() {
      return streamHumidity_;
    }
    /**
     * <code>double streamHumidity = 1;</code>
     */
    public Builder setStreamHumidity(double value) {
      
      streamHumidity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double streamHumidity = 1;</code>
     */
    public Builder clearStreamHumidity() {
      
      streamHumidity_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.grpc.humiditySensor.StreamHumidityRequest)
  }

  // @@protoc_insertion_point(class_scope:com.example.grpc.humiditySensor.StreamHumidityRequest)
  private static final com.example.grpc.humiditySensor.StreamHumidityRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.grpc.humiditySensor.StreamHumidityRequest();
  }

  public static com.example.grpc.humiditySensor.StreamHumidityRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamHumidityRequest>
      PARSER = new com.google.protobuf.AbstractParser<StreamHumidityRequest>() {
    @java.lang.Override
    public StreamHumidityRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StreamHumidityRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StreamHumidityRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StreamHumidityRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.grpc.humiditySensor.StreamHumidityRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

