// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: humiditySensor.proto

package com.example.grpc.humiditySensor;

public interface UnaryHumidityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.humiditySensor.UnaryHumidityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
