// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: humiditySensor.proto

package com.example.grpc.humiditySensor;

public interface UnaryHumidityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.humiditySensor.UnaryHumidityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double humidity = 1;</code>
   */
  double getHumidity();
}
