// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airHumiditySensor.proto

package com.example.grpc.airHumiditySensor;

public interface AirHumidityConnectionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.airHumiditySensor.AirHumidityConnectionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
