// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airHumiditySensor.proto

package com.example.grpc.airHumiditySensor;

/**
 * Protobuf type {@code com.example.grpc.airHumiditySensor.StreamAirHumidityRequest}
 */
public  final class StreamAirHumidityRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.grpc.airHumiditySensor.StreamAirHumidityRequest)
    StreamAirHumidityRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StreamAirHumidityRequest.newBuilder() to construct.
  private StreamAirHumidityRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StreamAirHumidityRequest() {
    airHumidity_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StreamAirHumidityRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            airHumidity_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.grpc.airHumiditySensor.airHumidityProto.internal_static_com_example_grpc_airHumiditySensor_StreamAirHumidityRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.grpc.airHumiditySensor.airHumidityProto.internal_static_com_example_grpc_airHumiditySensor_StreamAirHumidityRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.grpc.airHumiditySensor.StreamAirHumidityRequest.class, com.example.grpc.airHumiditySensor.StreamAirHumidityRequest.Builder.class);
  }

  public static final int AIRHUMIDITY_FIELD_NUMBER = 1;
  private int airHumidity_;
  /**
   * <code>int32 airHumidity = 1;</code>
   */
  public int getAirHumidity() {
    return airHumidity_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (airHumidity_ != 0) {
      output.writeInt32(1, airHumidity_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (airHumidity_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, airHumidity_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.grpc.airHumiditySensor.StreamAirHumidityRequest)) {
      return super.equals(obj);
    }
    com.example.grpc.airHumiditySensor.StreamAirHumidityRequest other = (com.example.grpc.airHumiditySensor.StreamAirHumidityRequest) obj;

    boolean result = true;
    result = result && (getAirHumidity()
        == other.getAirHumidity());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AIRHUMIDITY_FIELD_NUMBER;
    hash = (53 * hash) + getAirHumidity();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.grpc.airHumiditySensor.StreamAirHumidityRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.airHumiditySensor.StreamAirHumidityRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.airHumiditySensor.StreamAirHumidityRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.airHumiditySensor.StreamAirHumidityRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.airHumiditySensor.StreamAirHumidityRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.airHumiditySensor.StreamAirHumidityRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.airHumiditySensor.StreamAirHumidityRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.airHumiditySensor.StreamAirHumidityRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.airHumiditySensor.StreamAirHumidityRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.grpc.airHumiditySensor.StreamAirHumidityRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.airHumiditySensor.StreamAirHumidityRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.airHumiditySensor.StreamAirHumidityRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.grpc.airHumiditySensor.StreamAirHumidityRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.grpc.airHumiditySensor.StreamAirHumidityRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.grpc.airHumiditySensor.StreamAirHumidityRequest)
      com.example.grpc.airHumiditySensor.StreamAirHumidityRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.airHumiditySensor.airHumidityProto.internal_static_com_example_grpc_airHumiditySensor_StreamAirHumidityRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.airHumiditySensor.airHumidityProto.internal_static_com_example_grpc_airHumiditySensor_StreamAirHumidityRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.airHumiditySensor.StreamAirHumidityRequest.class, com.example.grpc.airHumiditySensor.StreamAirHumidityRequest.Builder.class);
    }

    // Construct using com.example.grpc.airHumiditySensor.StreamAirHumidityRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      airHumidity_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.grpc.airHumiditySensor.airHumidityProto.internal_static_com_example_grpc_airHumiditySensor_StreamAirHumidityRequest_descriptor;
    }

    @java.lang.Override
    public com.example.grpc.airHumiditySensor.StreamAirHumidityRequest getDefaultInstanceForType() {
      return com.example.grpc.airHumiditySensor.StreamAirHumidityRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.grpc.airHumiditySensor.StreamAirHumidityRequest build() {
      com.example.grpc.airHumiditySensor.StreamAirHumidityRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.grpc.airHumiditySensor.StreamAirHumidityRequest buildPartial() {
      com.example.grpc.airHumiditySensor.StreamAirHumidityRequest result = new com.example.grpc.airHumiditySensor.StreamAirHumidityRequest(this);
      result.airHumidity_ = airHumidity_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.grpc.airHumiditySensor.StreamAirHumidityRequest) {
        return mergeFrom((com.example.grpc.airHumiditySensor.StreamAirHumidityRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.grpc.airHumiditySensor.StreamAirHumidityRequest other) {
      if (other == com.example.grpc.airHumiditySensor.StreamAirHumidityRequest.getDefaultInstance()) return this;
      if (other.getAirHumidity() != 0) {
        setAirHumidity(other.getAirHumidity());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.grpc.airHumiditySensor.StreamAirHumidityRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.grpc.airHumiditySensor.StreamAirHumidityRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int airHumidity_ ;
    /**
     * <code>int32 airHumidity = 1;</code>
     */
    public int getAirHumidity() {
      return airHumidity_;
    }
    /**
     * <code>int32 airHumidity = 1;</code>
     */
    public Builder setAirHumidity(int value) {
      
      airHumidity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 airHumidity = 1;</code>
     */
    public Builder clearAirHumidity() {
      
      airHumidity_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.grpc.airHumiditySensor.StreamAirHumidityRequest)
  }

  // @@protoc_insertion_point(class_scope:com.example.grpc.airHumiditySensor.StreamAirHumidityRequest)
  private static final com.example.grpc.airHumiditySensor.StreamAirHumidityRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.grpc.airHumiditySensor.StreamAirHumidityRequest();
  }

  public static com.example.grpc.airHumiditySensor.StreamAirHumidityRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamAirHumidityRequest>
      PARSER = new com.google.protobuf.AbstractParser<StreamAirHumidityRequest>() {
    @java.lang.Override
    public StreamAirHumidityRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StreamAirHumidityRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StreamAirHumidityRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StreamAirHumidityRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.grpc.airHumiditySensor.StreamAirHumidityRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

