// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airHumiditySensor.proto

package com.example.grpc.airHumiditySensor;

public interface StreamAirHumidityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.airHumiditySensor.StreamAirHumidityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 airHumidity = 1;</code>
   */
  int getAirHumidity();
}
