// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registerData.proto

package com.example.grpc.registerDataService;

public final class registerDataServiceProto {
  private registerDataServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_registerDataService_SensorDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_registerDataService_SensorDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_registerDataService_SensorDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_registerDataService_SensorDataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022registerData.proto\022$com.example.grpc.r" +
      "egisterDataService\"P\n\021SensorDataRequest\022" +
      "\023\n\013temperature\030\001 \001(\005\022\024\n\014soilHumidity\030\002 \001" +
      "(\005\022\020\n\010dateTime\030\003 \001(\t\"%\n\022SensorDataRespon" +
      "se\022\017\n\007message\030\001 \001(\t2\226\001\n\023RegisterDataServ" +
      "ice\022\177\n\010sendData\0227.com.example.grpc.regis" +
      "terDataService.SensorDataRequest\0328.com.e" +
      "xample.grpc.registerDataService.SensorDa" +
      "taResponse(\001BB\n$com.example.grpc.registe" +
      "rDataServiceB\030registerDataServiceProtoP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_example_grpc_registerDataService_SensorDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_grpc_registerDataService_SensorDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_registerDataService_SensorDataRequest_descriptor,
        new java.lang.String[] { "Temperature", "SoilHumidity", "DateTime", });
    internal_static_com_example_grpc_registerDataService_SensorDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_grpc_registerDataService_SensorDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_registerDataService_SensorDataResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
