// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registerData.proto

package com.example.grpc.registerDataService;

public interface SensorDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.registerDataService.SensorDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
