// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registerData.proto

package com.example.grpc.registerDataService;

/**
 * Protobuf type {@code com.example.grpc.registerDataService.SensorDataRequest}
 */
public  final class SensorDataRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.grpc.registerDataService.SensorDataRequest)
    SensorDataRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SensorDataRequest.newBuilder() to construct.
  private SensorDataRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SensorDataRequest() {
    temperature_ = 0;
    soilHumidity_ = 0;
    dateTime_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SensorDataRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            temperature_ = input.readInt32();
            break;
          }
          case 16: {

            soilHumidity_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            dateTime_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.grpc.registerDataService.registerDataServiceProto.internal_static_com_example_grpc_registerDataService_SensorDataRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.grpc.registerDataService.registerDataServiceProto.internal_static_com_example_grpc_registerDataService_SensorDataRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.grpc.registerDataService.SensorDataRequest.class, com.example.grpc.registerDataService.SensorDataRequest.Builder.class);
  }

  public static final int TEMPERATURE_FIELD_NUMBER = 1;
  private int temperature_;
  /**
   * <code>int32 temperature = 1;</code>
   */
  public int getTemperature() {
    return temperature_;
  }

  public static final int SOILHUMIDITY_FIELD_NUMBER = 2;
  private int soilHumidity_;
  /**
   * <code>int32 soilHumidity = 2;</code>
   */
  public int getSoilHumidity() {
    return soilHumidity_;
  }

  public static final int DATETIME_FIELD_NUMBER = 3;
  private volatile java.lang.Object dateTime_;
  /**
   * <code>string dateTime = 3;</code>
   */
  public java.lang.String getDateTime() {
    java.lang.Object ref = dateTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dateTime_ = s;
      return s;
    }
  }
  /**
   * <code>string dateTime = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDateTimeBytes() {
    java.lang.Object ref = dateTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dateTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (temperature_ != 0) {
      output.writeInt32(1, temperature_);
    }
    if (soilHumidity_ != 0) {
      output.writeInt32(2, soilHumidity_);
    }
    if (!getDateTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dateTime_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (temperature_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, temperature_);
    }
    if (soilHumidity_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, soilHumidity_);
    }
    if (!getDateTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, dateTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.grpc.registerDataService.SensorDataRequest)) {
      return super.equals(obj);
    }
    com.example.grpc.registerDataService.SensorDataRequest other = (com.example.grpc.registerDataService.SensorDataRequest) obj;

    boolean result = true;
    result = result && (getTemperature()
        == other.getTemperature());
    result = result && (getSoilHumidity()
        == other.getSoilHumidity());
    result = result && getDateTime()
        .equals(other.getDateTime());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
    hash = (53 * hash) + getTemperature();
    hash = (37 * hash) + SOILHUMIDITY_FIELD_NUMBER;
    hash = (53 * hash) + getSoilHumidity();
    hash = (37 * hash) + DATETIME_FIELD_NUMBER;
    hash = (53 * hash) + getDateTime().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.grpc.registerDataService.SensorDataRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.registerDataService.SensorDataRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.registerDataService.SensorDataRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.registerDataService.SensorDataRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.registerDataService.SensorDataRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.registerDataService.SensorDataRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.registerDataService.SensorDataRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.registerDataService.SensorDataRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.registerDataService.SensorDataRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.grpc.registerDataService.SensorDataRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.registerDataService.SensorDataRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.registerDataService.SensorDataRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.grpc.registerDataService.SensorDataRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.grpc.registerDataService.SensorDataRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.grpc.registerDataService.SensorDataRequest)
      com.example.grpc.registerDataService.SensorDataRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.registerDataService.registerDataServiceProto.internal_static_com_example_grpc_registerDataService_SensorDataRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.registerDataService.registerDataServiceProto.internal_static_com_example_grpc_registerDataService_SensorDataRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.registerDataService.SensorDataRequest.class, com.example.grpc.registerDataService.SensorDataRequest.Builder.class);
    }

    // Construct using com.example.grpc.registerDataService.SensorDataRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      temperature_ = 0;

      soilHumidity_ = 0;

      dateTime_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.grpc.registerDataService.registerDataServiceProto.internal_static_com_example_grpc_registerDataService_SensorDataRequest_descriptor;
    }

    @java.lang.Override
    public com.example.grpc.registerDataService.SensorDataRequest getDefaultInstanceForType() {
      return com.example.grpc.registerDataService.SensorDataRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.grpc.registerDataService.SensorDataRequest build() {
      com.example.grpc.registerDataService.SensorDataRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.grpc.registerDataService.SensorDataRequest buildPartial() {
      com.example.grpc.registerDataService.SensorDataRequest result = new com.example.grpc.registerDataService.SensorDataRequest(this);
      result.temperature_ = temperature_;
      result.soilHumidity_ = soilHumidity_;
      result.dateTime_ = dateTime_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.grpc.registerDataService.SensorDataRequest) {
        return mergeFrom((com.example.grpc.registerDataService.SensorDataRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.grpc.registerDataService.SensorDataRequest other) {
      if (other == com.example.grpc.registerDataService.SensorDataRequest.getDefaultInstance()) return this;
      if (other.getTemperature() != 0) {
        setTemperature(other.getTemperature());
      }
      if (other.getSoilHumidity() != 0) {
        setSoilHumidity(other.getSoilHumidity());
      }
      if (!other.getDateTime().isEmpty()) {
        dateTime_ = other.dateTime_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.grpc.registerDataService.SensorDataRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.grpc.registerDataService.SensorDataRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int temperature_ ;
    /**
     * <code>int32 temperature = 1;</code>
     */
    public int getTemperature() {
      return temperature_;
    }
    /**
     * <code>int32 temperature = 1;</code>
     */
    public Builder setTemperature(int value) {
      
      temperature_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 temperature = 1;</code>
     */
    public Builder clearTemperature() {
      
      temperature_ = 0;
      onChanged();
      return this;
    }

    private int soilHumidity_ ;
    /**
     * <code>int32 soilHumidity = 2;</code>
     */
    public int getSoilHumidity() {
      return soilHumidity_;
    }
    /**
     * <code>int32 soilHumidity = 2;</code>
     */
    public Builder setSoilHumidity(int value) {
      
      soilHumidity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 soilHumidity = 2;</code>
     */
    public Builder clearSoilHumidity() {
      
      soilHumidity_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object dateTime_ = "";
    /**
     * <code>string dateTime = 3;</code>
     */
    public java.lang.String getDateTime() {
      java.lang.Object ref = dateTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dateTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dateTime = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDateTimeBytes() {
      java.lang.Object ref = dateTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dateTime = 3;</code>
     */
    public Builder setDateTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dateTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dateTime = 3;</code>
     */
    public Builder clearDateTime() {
      
      dateTime_ = getDefaultInstance().getDateTime();
      onChanged();
      return this;
    }
    /**
     * <code>string dateTime = 3;</code>
     */
    public Builder setDateTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dateTime_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.grpc.registerDataService.SensorDataRequest)
  }

  // @@protoc_insertion_point(class_scope:com.example.grpc.registerDataService.SensorDataRequest)
  private static final com.example.grpc.registerDataService.SensorDataRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.grpc.registerDataService.SensorDataRequest();
  }

  public static com.example.grpc.registerDataService.SensorDataRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SensorDataRequest>
      PARSER = new com.google.protobuf.AbstractParser<SensorDataRequest>() {
    @java.lang.Override
    public SensorDataRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SensorDataRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SensorDataRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SensorDataRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.grpc.registerDataService.SensorDataRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

