// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fanService.proto

package com.example.grpc.fanService;

public final class fanServiceProto {
  private fanServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_fanService_StreamTemperatureToFan_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_fanService_StreamTemperatureToFan_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_fanService_StreamFanStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_fanService_StreamFanStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020fanService.proto\022\033com.example.grpc.fan" +
      "Service\"-\n\026StreamTemperatureToFan\022\023\n\013tem" +
      "perature\030\001 \001(\005\"\"\n\017StreamFanStatus\022\017\n\007mes" +
      "sage\030\001 \001(\t2\201\001\n\nFanService\022s\n\nfanService\022" +
      "3.com.example.grpc.fanService.StreamTemp" +
      "eratureToFan\032,.com.example.grpc.fanServi" +
      "ce.StreamFanStatus(\0010\001B0\n\033com.example.gr" +
      "pc.fanServiceB\017fanServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_example_grpc_fanService_StreamTemperatureToFan_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_grpc_fanService_StreamTemperatureToFan_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_fanService_StreamTemperatureToFan_descriptor,
        new java.lang.String[] { "Temperature", });
    internal_static_com_example_grpc_fanService_StreamFanStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_grpc_fanService_StreamFanStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_fanService_StreamFanStatus_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
