// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fanService.proto

package com.example.grpc.fanService;

public interface StreamTemperatureToFanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.fanService.StreamTemperatureToFan)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 temperature = 1;</code>
   */
  int getTemperature();
}
