// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temperatureSensor.proto

package com.example.grpc.temperatureSensor;

public interface StreamTemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.temperatureSensor.StreamTemperatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double streamTemperature = 1;</code>
   */
  double getStreamTemperature();
}
