// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temperatureSensor.proto

package com.example.grpc.temperatureSensor;

public final class temperatureProto {
  private temperatureProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_temperatureSensor_TemperatureConnectionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_temperatureSensor_TemperatureConnectionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_temperatureSensor_TemperatureConnectionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_temperatureSensor_TemperatureConnectionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_temperatureSensor_StreamTemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_temperatureSensor_StreamTemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_temperatureSensor_StreamTemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_temperatureSensor_StreamTemperatureResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027temperatureSensor.proto\022\"com.example.g" +
      "rpc.temperatureSensor\"3\n\034TemperatureConn" +
      "ectionRequest\022\023\n\013temperature\030\001 \001(\005\"0\n\035Te" +
      "mperatureConnectionResponse\022\017\n\007message\030\001" +
      " \001(\t\"/\n\030StreamTemperatureRequest\022\023\n\013temp" +
      "erature\030\001 \001(\005\"A\n\031StreamTemperatureRespon" +
      "se\022\017\n\007message\030\001 \001(\t\022\023\n\013temperature\030\002 \001(\005" +
      "2\333\002\n\033TemperatureSensorConnection\022\237\001\n\030get" +
      "TemperatureConnection\022@.com.example.grpc" +
      ".temperatureSensor.TemperatureConnection" +
      "Request\032A.com.example.grpc.temperatureSe" +
      "nsor.TemperatureConnectionResponse\022\231\001\n\030s" +
      "treamCurrentTemperature\022<.com.example.gr" +
      "pc.temperatureSensor.StreamTemperatureRe" +
      "quest\032=.com.example.grpc.temperatureSens" +
      "or.StreamTemperatureResponse0\001B8\n\"com.ex" +
      "ample.grpc.temperatureSensorB\020temperatur" +
      "eProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_example_grpc_temperatureSensor_TemperatureConnectionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_grpc_temperatureSensor_TemperatureConnectionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_temperatureSensor_TemperatureConnectionRequest_descriptor,
        new java.lang.String[] { "Temperature", });
    internal_static_com_example_grpc_temperatureSensor_TemperatureConnectionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_grpc_temperatureSensor_TemperatureConnectionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_temperatureSensor_TemperatureConnectionResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_example_grpc_temperatureSensor_StreamTemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_grpc_temperatureSensor_StreamTemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_temperatureSensor_StreamTemperatureRequest_descriptor,
        new java.lang.String[] { "Temperature", });
    internal_static_com_example_grpc_temperatureSensor_StreamTemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_example_grpc_temperatureSensor_StreamTemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_temperatureSensor_StreamTemperatureResponse_descriptor,
        new java.lang.String[] { "Message", "Temperature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
