// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temperatureSensor.proto

package com.example.grpc.temperatureSensor;

public interface TemperatureConnectionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.temperatureSensor.TemperatureConnectionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 temperature = 1;</code>
   */
  int getTemperature();
}
