// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temperatureSensor.proto

package com.example.grpc.temperatureSensor;

public interface TemperatureConnectionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.temperatureSensor.TemperatureConnectionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serverName = 1;</code>
   */
  java.lang.String getServerName();
  /**
   * <code>string serverName = 1;</code>
   */
  com.google.protobuf.ByteString
      getServerNameBytes();
}
