// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temperatureSensor.proto

package com.example.grpc.temperatureSensor;

public interface UnaryTemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.temperatureSensor.UnaryTemperatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double temperature = 1;</code>
   */
  double getTemperature();
}
